apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: "argo-cd"
    repo: "https://argoproj.github.io/argo-helm"
    chart: "argo-cd"
    version: "5.27.3"
    releaseName: "argocd"
    namespace: "argocd"
    valuesFile: "values.yaml"

resources:
  - argocd-ingressroute.yaml
