apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable
- base/argocd-cert.yaml
- base/argocd-ingressroute.yaml

patches:
- path: overlays/argocd-cmd-params-cm.yaml