apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/diogoazevedo15/home-lab.git'
    targetRevision: 'main'
    path: 'infrastructure/cluster-issuer'
    directory:
      recurse: true
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
